


modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1:Brower", "2:Code", "3:Term", "4:File", "5:Chat", "6:Video", "7:ﱘMusic", "8:Graphics", "9:♖System"]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "GridHorizontal", "EvenHorizontal", "EvenVertical", "LeftMain", "RightWiderLeftStack", "LeftWiderRightStack"]
layout_mode = "Workspace"
insert_behavior = "Bottom"
# scratchpad = []
scratchpad = [
    { name = "ST", value = "st", x = 860, y = 390, height = 300, width = 200 },
]
# window_rules = []
window_rules = [
  # windows whose WM_CLASS is "Navigator" will be spawn on tag 2 (by position, 1-indexed)
  {window_class = "google-chrome-stable", spawn_on_tag = 1},
  # windows whose window title is "Pentablet" will be spawned floating on tag 9
  {window_title = "Pentablet", spawn_on_tag = 9, spawn_floating = true},
]
disable_current_tag_swap = false
disable_tile_drag = false
disable_window_snap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

#===================== APP =========================================

# google-chrome-stable
[[keybind]]
command = "Execute"
value = "google-chrome-stable"
modifier = ["modkey"]
key = "g"


# thunar
[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey"]
key = "n"


# thunar
[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey"]
key = "t"

# thunar
[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey","Shift"]
key = "t"


#==================================  系统快捷键 ===============================================
# dmenu
[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "d"

#ST
[[keybind]]
command = "Execute"
value = "st"
modifier = ["modkey"]
key = "Return"

#rofi
[[keybind]]
command = "Execute"
value = "rofi  -show  combi"
modifier = ["modkey"]
key = "r"

# xterm
[[keybind]]
command = "Execute"
value = "xterm"
modifier = ["modkey"]
key = "x"


#关闭当前窗口
[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey", "Shift"]
key = "q"

# 重启WM而不离开
[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Control"]
key = "r"

[[keybind]]
command = "HardReload"
modifier = ["modkey", "Control"]
key = "q"

# 离开leftWM
[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Control"]
key = "e"



# slock锁屏
[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

# 锁屏
[[keybind]]
command = "Execute"
value = "xscreensaver-command --lock"
modifier = ["modkey", "Control"]
key = "x"


# 锁屏
[[keybind]]
command = "Execute"
value = "betterlockscreen -l"
modifier = ["modkey", "Control"]
key = "b"



#==========================  在同一个桌面内移动窗口 =====================================================
#将当前窗口向上移动
# Re-orders the focused window within the current workspace (moves up in order).
[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"


#将当前窗口向上移动
[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "period"

#将当前窗口向下移动
# Re-orders the focused window within the current workspace (moves down in order).
[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

#将当前窗口向下移动
[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"



#将当前窗口向下移动
[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "comma"

#移动当前窗口到Master,将当前窗口提升为主窗口,或反过来，双向命令
[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey", "Control"]
key = "Return"


# 增加窗口宽度
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "equal"


# 减少窗口宽度
[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "minus"



#全屏
[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

#==========================  在同一个桌面内移动窗口over =====================================================


#==========================  窗口间切换 =====================================================
#聚焦于上一个窗口
[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"
#聚焦于上一个窗口
[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"
#聚焦于上一个窗口
[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "w"

#聚焦于上一个窗口
[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "period"

#聚焦于下一个窗口
[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

#聚焦于下一个窗口
[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "q"



#聚焦于下一个窗口
[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "comma"

# 在当前窗口和主窗口间来回切换
#[[keybind]]
#command = "FocusWindowTop"
#modifier = ["modkey","Shift"]
#value = true
#key = "Return"

#==========================  窗口间切换 over=====================================================



#==========================  在显示器间切换焦点，在不显示器(屏幕)间移动当前窗口 =====================================================



# 将当前窗口移动到下一个显示器
[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey", "Control"]
key = "bracketright"



# 将当前窗口移动到上一个显示器
[[keybind]]
command = "MoveWindowToPreviousWorkspace"
modifier = ["modkey", "Control"]
key = "bracketleft"


#聚焦于下一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "l"

#聚焦于下一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

#聚焦于下一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "bracketright"

#聚焦于上一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "h"

#聚焦于上一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "bracketleft"

#聚焦于上一个聚焦的口，在最近聚焦的两个窗口来回切换
[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"


# 将当前窗口在最近的桌面与当前桌面来回切换并聚焦,和i3类似
[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "b"


#==========================  桌面间切换 =====================================================
# 在当前桌面和上次聚焦的桌面来回切换
[[keybind]]
command = "ReturnToLastTag"
modifier = ["modkey"]
key = "b"

#聚焦于下一个桌面tag
[[keybind]]
command = "FocusNextTag"
modifier = ["modkey","Shift"]
key = "l"

#聚焦于下一个桌面tag
[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "quoteright"



#聚焦于上一个桌面tag
[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey","Shift"]
key = "h"



#聚焦于上一个桌面tag
[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "semicolon"

# Switch the desktops for each screen. Desktops [1][2] changes to [2][1]
[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey","Shift"]
key = "w"

#==========================  桌面布局方式layouts =====================================================

# 下一个桌面的布局方式循环
[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Shift"]
key = "space"

# 上一个桌面的布局方式循环
[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "space"

# 将当前窗口在浮动和平铺模式双向切换
[[keybind]]
command = "ToggleFloating"
modifier = ["modkey" ]
key = "space"


#将当前窗口从浮动变为平铺
[[keybind]]
command = "FloatingToTile"
modifier = ["modkey", "Shift"]
key = "t"

#将当前窗口从平铺变为浮动
[[keybind]]
command = "TileToFloating"
modifier = ["modkey", "Shift"]
key = "f"


# 使得当前窗口跟随鼠标的聚焦，鼠标到哪个桌面当前窗口就到哪个
[[keybind]]
command = "ToggleSticky"
modifier = ["modkey","Shift"]
key = "s"


# 旋转窗口布局方式
[[keybind]]
command = "RotateTag"
modifier = ["modkey"]
key = "z"


# 调整窗口间的距离
[[keybind]]
command = "SetMarginMultiplier"
value = "0.5"
modifier = ["modkey"]
key = "m"


[[keybind]]
command = "ToggleScratchPad"
value = "ST" # Name set for the scratchpad
modifier = ["modkey"]
key = "p"

#==============================  查看标签页======================================================
# 查看标签页
[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

#==============================  将当前窗口移动到指定标签页======================================================

#将当前窗口移动到指定标签页
[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"
