border_width = 2
margin = 10
default_border_color = "#222222"
floating_border_color = "#555555"
# focused_border_color = "#00FF00"
# focused_border_color = "#0000FF"
# focused_border_color = "#2d41a3"
focused_border_color = "#1E90FF"



