#!/usr/bin/env bash


export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo $( cd "$(dirname "$0")" ; pwd -P )

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom -b &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"


#set background
if [ -x "$(command -v feh)" ]; then
  #feh --bg-scale $SCRIPTPATH/background.jpg
  feh --recursive --randomize --bg-fill   $SCRIPTPATH/'/wallpapers/'
fi

index=0
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read size
do
   leftwm-state -w $index -t $SCRIPTPATH/template.liquid | xmobar -p "$size" $SCRIPTPATH/xmobarrc.hs &
   let index=index+1
done

leftwm-command "SetMarginMultiplier 0.2"

# tray icons(eDP1 is the display device's name, use the command "xrandr" to see the display device name.)
# 其中的eDP1便是我的显示设备名称。如果你的显示设备名称不是eDP1 ，那么需要修改
# xrandr --output eDP-1 --primary

# 如果为笔记本外接两个显示器，关闭笔记本的显示器
# xrandr --output DP-1-8 --mode 1920x1080 --primary
# xrandr --output DP-1-9 --mode 1920x1080  --right-of DP-1-8  --auto
# xrandr  --output eDP-1 --off


# 如果为笔记本外接1个显示器
#  xrandr --output eDP-1 --mode 1920x1080 --primary
# xrandr --output HDMI1 1920*1080 --right-of eDP1



# 如果为台式机外接2个显示器
# xrandr --output HDM-1 --mode 1920x1080 --primary
#  xrandr --output HDMI-2  1920*1080 --right-of HDM-1


# feh --recursive --randomize --bg-fill   $(xdg-user-dir PICTURES)'/Wallpapers/'
# feh --recursive  --bg-fill $(xdg-user-dir PICTURES)'/Wallpapers/background.jpg'


# Power manager
if [ -z "$(pgrep xfce4-power-manager)" ] ; then
    xfce4-power-manager &
fi




# Network Applet用于显示网络托盘图标，
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet &
fi


# blue Applet蓝牙系统托盘
if [ -z "$(pgrep blueman-applet)" ] ; then
    blueman-applet &
fi

# Screensaver 锁屏工具
if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver -no-splash &
fi


# Redshift
# 护眼工具
if [ -z "$(pgrep redshift)" ] ; then
    redshift-gtk &
fi

# 启用窗口透明
if [ -z "$(pgrep picom)" ] ; then
    picom --experimental-backends -b
fi


# 火焰截图
if [ -z "$(pgrep   flameshot)" ] ; then
    nohup flameshot >/dev/null 2>&1  &
fi


# 桌面通知
if [ -z "$(pgrep   dunst)" ] ; then
    dunst &
fi



# 剪切板管理器
if [ -z "$(pgrep  copyq )" ] ; then
    copyq &
fi



# 开启小键盘
if [ -z "$(pgrep   numlockx)" ] ; then
   numlockx on
fi


if [ -z "$(pgrep  fcitx )" ] ; then
    fcitx   &
    fcitx5   &
fi



#音频相关的托盘
if [ -z "$(pgrep  pasystray )" ] ; then
     nohup   pasystray     >  /dev/null  2>&1 &
fi


if [ -z "$(pgrep  kmix )" ] ; then
     nohup   kmix     >  /dev/null  2>&1 &
fi


if [ -z "$(pgrep  pa-applet )" ] ; then
     nohup   /foo/bar/bin/pa-applet       >  /dev/null  2>&1 &
fi

if [ -z "$(pgrep  mictray )" ] ; then
     nohup   mictray       >  /dev/null  2>&1 &
fi


#  xautolock锁屏工具
if [ -z "$(pgrep  xautolock)" ] ; then
     xautolock -time 30 -locker '/usr/bin/betterlockscreen -l'   -corners +000 -cornersize 5 -cornerdelay 5 -cornerredelay 180 &
fi

sleep 5

killall conky

#  xautolock锁屏工具
if [ -z "$(pgrep  conky)" ] ; then
    echo  ""
else
    killall conky
fi


## System tray
if [ -z "$(pgrep trayer)" ] ; then
    trayer --edge top --align right --widthtype percent --width 13 --heighttype pixel --height 23  --SetPartialStrut true --transparent true --alpha 60 --tint 0x777777 --expand true  --expand true --distance 0 --padding 0
fi


# if [ -z "$(pgrep stalonetray)" ] ; then
#     stalonetray  -geometry  "12x1-0+0" -bg "#777777" --icon-size 17 --transparent false --sticky true --window-layer "bottom"  &
# fi


